Post
RobertMex/KaskaritaApp pull request #2
Opened 2021-07-15 16:45 UTC by RobertMex

User can create and see posts. At the moment the implementation is basic, later more functionalities will be added.

![image](https://user-images.githubusercontent.com/70187422/125825661-6f1ea7d2-4349-4f0a-8308-c0bc940cc0f4.png)

2021-07-15 20:12 UTC, SantiCe requested changes
This is very solid! The thing works and it looks cool!
Nice job getting camera integration right away.

I've left some comments. Please try to address some of them, or create tasks to fix later. There are some quick things that we can do to make the code a bit cleaner.

2021-07-15 20:12 UTC, SantiCe commented on app/src/main/java/com/example/kaskarita/ui/creation/CreationFragment.java
> +            }
Should we go to the main activity here?

2021-07-15 20:12 UTC, SantiCe commented on app/src/main/java/com/example/kaskarita/ui/creation/CreationFragment.java
> +        Uri fileProvider = FileProvider.getUriForFile(getActivity(), "com.kaskarita.fileprovider", photoFile);
strong suggestion: Please declare `com.kaskarita.fileprovider` as a constant.

2021-07-15 20:12 UTC, SantiCe commented on app/src/main/java/com/example/kaskarita/ui/home/HomeFragment.java
> +        query.setLimit(20);
strong suggestion: Please declare this `20` as a constant.
```
private static final int NUM_POSTS_TO_SHOW = 20
```

2021-07-15 20:12 UTC, SantiCe commented on app/src/main/java/com/example/kaskarita/Post.java
> +public class Post extends ParseObject {
nit: Call this `ParsePost` to signal that this is the parse object?

2021-07-15 20:12 UTC, SantiCe commented on app/src/main/java/com/example/kaskarita/ui/home/HomeFragment.java
> +        query.setLimit(20);
So you only get to see the latest 20?
Do you have plans to implement something so that if you for example pull-down if you are at the end, the next 20 posts show up? I think this could be a good thing to add.

Again, not right now, but good to create a task and have it present.

2021-07-15 20:12 UTC, SantiCe commented on app/src/main/java/com/example/kaskarita/ui/home/HomeFragment.java
> +        query.addDescendingOrder("createdAt");
Please declare this as a constant. I think the correct place to declare it would be at the `Post` class:
```
public static final String KEY_CREATED_AT = "createdAt";
```

2021-07-15 20:12 UTC, SantiCe commented on app/src/main/java/com/example/kaskarita/ui/home/HomeFragment.java
> +        ParseQuery<Post> query = ParseQuery.getQuery(Post.class);
aside: Let's chat about containing Parse details in a single place and not having all components have to know parse.

2021-07-15 21:08 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/LoginActivity.java
> -                //finish();
In the new commits that line is already eliminated, I did not consider it, because I did not see it necessary for the user to return to the LoginActivity without logout.

2021-07-15 21:11 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/ParseApplication.java
>                  .applicationId("KEA2q76Ryyqm2BJlqNtjkNsB9shqxqe34z1CJW6v")
Thanks for the suggestion, the change has already been made for the new commit.

2021-07-15 21:13 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/ParseApplication.java
>                  .clientKey("bG0uOjFk0sCRvnYOmt4FiJK1F9r2YkBXTUbIWL1O")
Thanks for the suggestion!

2021-07-15 21:15 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/Post.java
> +    //public static final String KEY_LOCATION = "location";
Ok

2021-07-15 21:16 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/Post.java
> +    public static final String KEY_DESCRIPTION = "description";
Thanks

2021-07-15 21:30 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/PostsAdapter.java
> +        Post post = posts.get(position);
Well, there will be cases that we will not have any post, so nothing will be shown in RecyclerView

2021-07-15 21:30 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/PostsAdapter.java
> +        int SECOND_MILLIS = 1000;
Ok, thanks!

2021-07-15 21:34 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/ui/creation/CreationFragment.java
> +    private Button btnCaptureImage;
Thats sounds good.

2021-07-15 21:40 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/ui/creation/CreationFragment.java
> +            }
Are you referring to the HomeFragment? And if so, it sounds good, I had not considered it.

2021-07-15 21:46 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/ui/creation/CreationFragment.java
> +        Uri fileProvider = FileProvider.getUriForFile(getActivity(), "com.kaskarita.fileprovider", photoFile);
Ok

2021-07-15 21:47 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/ui/home/HomeFragment.java
> +        query.setLimit(20);
Thanks!

2021-07-15 21:53 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/Post.java
> +public class Post extends ParseObject {
As we have different data, we have it in a Parse object

2021-07-15 21:54 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/ui/home/HomeFragment.java
> +        query.setLimit(20);
In the new commit I already have implemented for Endless posts. Thanks!

2021-07-15 22:02 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/ui/home/HomeFragment.java
> +        query.addDescendingOrder("createdAt");
Ok

2021-07-15 22:03 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/ui/home/HomeFragment.java
> +        ParseQuery<Post> query = ParseQuery.getQuery(Post.class);
Perfect, thanks!

2021-07-15 22:38 UTC, SantiCe commented on app/src/main/java/com/example/kaskarita/ui/creation/CreationFragment.java
> +    private EditText etCategory;
suggestion: Can do this at a later point, but what do you think about making Category a drop-down instead of a free-text field?

That might make it easier later if you want to filter by category.

2021-07-15 22:45 UTC, RobertMex commented on app/src/main/java/com/example/kaskarita/ui/creation/CreationFragment.java
> +    private EditText etCategory;
Yes, my idea is to later implement the category in the drop-down menu, right now I put it in free text just to know what goes there.

2021-07-15 22:50 UTC, SantiCe commented on app/src/main/java/com/example/kaskarita/ui/creation/CreationFragment.java
> +    private EditText etCategory;
Sounds good! Please file a task for this.

2021-07-16 22:02 UTC, SantiCe approved these changes

2021-07-16 22:02 UTC, SantiCe commented
Nice. Looks good to me. Thanks for addressing the comments.

2021-07-18 22:03 UTC, merged